"""indices de rendimiento

Revision ID: 4b55ba224f0b
Revises: ddac4cb8e962
Create Date: 2026-09-14 10:14:15.856032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b55ba224f0b'
down_revision: Union[str, Sequence[str], None] = 'ddac4cb8e962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artist_connections_artist_id'), 'artist_connections', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_media_artist_id'), 'artist_media', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_metrics_artist_id'), 'artist_metrics', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_social_links_artist_id'), 'artist_social_links', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_timeline_artist_id'), 'artist_timeline', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artists_active'), 'artists', ['active'], unique=False)
    op.create_index(op.f('ix_collaborator_activities_collaborator_id'), 'collaborator_activities', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_publications_author_id'), 'publications', ['author_id'], unique=False)
    op.create_index(op.f('ix_publications_category_id'), 'publications', ['category_id'], unique=False)
    op.create_index('ix_publications_status_deleted', 'publications', ['status', 'deleted'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_collaborator_id'), 'reward_redemptions', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_suggestions_created_at'), 'suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_suggestions_status'), 'suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_tracks_artist_id'), 'tracks', ['artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_artist_id'), table_name='tracks')
    op.drop_index(op.f('ix_suggestions_status'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_created_at'), table_name='suggestions')
    op.drop_index(op.f('ix_reward_redemptions_collaborator_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index('ix_publications_status_deleted', table_name='publications')
    op.drop_index(op.f('ix_publications_category_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_author_id'), table_name='publications')
    op.drop_index(op.f('ix_collaborator_activities_collaborator_id'), table_name='collaborator_activities')
    op.drop_index(op.f('ix_artists_active'), table_name='artists')
    op.drop_index(op.f('ix_artist_timeline_artist_id'), table_name='artist_timeline')
    op.drop_index(op.f('ix_artist_social_links_artist_id'), table_name='artist_social_links')
    op.drop_index(op.f('ix_artist_metrics_artist_id'), table_name='artist_metrics')
    op.drop_index(op.f('ix_artist_media_artist_id'), table_name='artist_media')
    op.drop_index(op.f('ix_artist_connections_artist_id'), table_name='artist_connections')
    # ### end Alembic commands ###
