"""categoria cultural en publicaciones y foto de organizacion

Revision ID: 8676ea0b7099
Revises: e3e56e002800
Create Date: 2026-10-03 19:00:10.144945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8676ea0b7099'
down_revision: Union[str, Sequence[str], None] = 'e3e56e002800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('cultural_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'cultural_category')
    op.drop_column('organizations', 'photo_url')
    # ### end Alembic commands ###
