"""fechas de contenido a tipos reales

Revision ID: dcbcecf08b2c
Revises: 4b55ba224f0b
Create Date: 2026-09-14 23:15:41.016057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcbcecf08b2c'
down_revision: Union[str, Sequence[str], None] = '4b55ba224f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Postgres no castea VARCHAR -> DATE/TIMESTAMP de forma implicita en un
    ALTER COLUMN; hace falta un USING explicito. Se verifico antes de escribir
    esta migracion que el 100% de los datos reales en `public` ya son NULL o
    ISO 8601 valido (fecha sola o fecha+hora), asi que el cast directo con
    ::date / ::timestamp no deberia fallar ni truncar nada.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_media', 'fecha',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='fecha::date')
    op.alter_column('artist_metrics', 'fecha',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='fecha::date')
    op.alter_column('artist_timeline', 'fecha',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='fecha::date')
    op.alter_column('opportunities', 'deadline',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='deadline::timestamp')
    op.alter_column('publications', 'start_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='start_date::timestamp')
    op.alter_column('publications', 'end_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='end_date::timestamp')
    op.alter_column('tracks', 'release_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='release_date::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Nota: Date::text produce "YYYY-MM-DD" (identico al original), pero
    DateTime::text produce "YYYY-MM-DD HH:MI:SS" (espacio, no "T", y con
    segundos) en vez del formato "YYYY-MM-DDTHH:MM" que se escribia antes --
    diferencia cosmetica aceptable para una ruta de rollback, no afecta que
    el valor siga siendo un ISO 8601 parseable.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'release_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='release_date::varchar')
    op.alter_column('publications', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='end_date::varchar')
    op.alter_column('publications', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='start_date::varchar')
    op.alter_column('opportunities', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='deadline::varchar')
    op.alter_column('artist_timeline', 'fecha',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='fecha::varchar')
    op.alter_column('artist_metrics', 'fecha',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='fecha::varchar')
    op.alter_column('artist_media', 'fecha',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='fecha::varchar')
    # ### end Alembic commands ###
